services: 
  mysql:
    image: mysql
    env_file:
      - .env
    ports:
      - '3306:3306'

  redis:
    image: redis:latest
    restart: always
    env_file:
      - .env
    ports:
      - '6379:6379'
    # volumes:
      # - /path/to/local/d–∞ta:/root/redis
      # - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
